package com.svnitsai.gm.SMS;

/*
 * SMS_Error.java
 * 
 * @author: 	SVN Systems and Innovations
 * 
 * @purpose: 	Enum containing the list of errors generated by backend SMS processing
 * 
 */

public enum SMS_Error {
	  HTTP_POST_FAILED					(0001, "Http post failed"), //UI Specific message - contact Admin
	  HTTP_SEND_SMS_REQUEST_FAILED		(0002, "SMS Request failed at vendor side"), //UI Specific message - correctable
	  
	  PROPERTY_FILE_NOT_FOUND			(3001, "Property File not found"),
	  PROPERTY_NOT_FOUND				(3002, "Property not found"),

	  HTTP_IO_EXCEPTION					(8002, "Http I/O Exception"),
	  HTTP_EMPTY_REQUEST				(8003, "Http Empty Request XML"),
	  HTTP_INVALID_REQUEST_XML			(8004, "Invalid Request XML"),
	  HTTP_INVALID_REQUEST_URL			(8005, "Invalid Request URL"),

	  SMS_XML_RESPONSE_PARSE_ERROR		(8501, "Invalid / Unexpected Response XML"),
	  SMS_XML_REQUEST_PARSE_ERROR		(8502, "Invalid / Unexpected Request XML"),
	  SMS_INVALID_USERID_PASSWORD		(8503, "Invalid SMS userid / password"),

	  FILE_OPEN_EXCEPTION				(9001, "File could not be opened"),
	  
	  GENERIC_SYSTEM_ERROR 				(9999, "System Error Encountered")
	  ;
	  //... add more cases here ...

	  private final int id;
	  private final String message;

	  SMS_Error(int id, String message) {
	     this.id = id;
	     this.message = message;
	  }

	  public int getId() { return id; }
	  public String getMessage() { return message; }
}
